import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByPlaceholder('Username').click();
  await page.getByPlaceholder('Username').click();
  await page.getByText('Username : Admin').click();
  await page.getByPlaceholder('Username').click();
  await page.getByPlaceholder('Username').fill('');
  await page.getByPlaceholder('Username').press('CapsLock');
  await page.getByPlaceholder('Username').fill('A');
  await page.getByPlaceholder('Username').press('CapsLock');
  await page.getByPlaceholder('Username').fill('Admin');
  await page.getByPlaceholder('Username').press('Tab');
  await page.getByPlaceholder('Password').fill('admin123');
  await page.getByText('UsernamePassword Login Forgot').click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'PIM' }).click();
  await page.getByRole('link', { name: 'Add Employee' }).click();
  await page.getByPlaceholder('First Name').click();
  await page.getByPlaceholder('First Name').fill('ship');
  await page.getByPlaceholder('Middle Name').click();
  await page.getByPlaceholder('Middle Name').fill('bbb');
  await page.getByPlaceholder('Last Name').click();
  await page.getByPlaceholder('Last Name').fill('ccc');
  await page.locator('form').getByRole('textbox').nth(4).click();
  await page.locator('form').getByRole('textbox').nth(4).fill('88888888');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('div').filter({ hasText: /^Driver's License NumberLicense Expiry Date$/ }).getByRole('textbox').first().click();
  await page.locator('div').filter({ hasText: /^Driver's License NumberLicense Expiry Date$/ }).getByRole('textbox').first().fill('454yui');
  await page.locator('div').filter({ hasText: /^Driver's License NumberLicense Expiry Date$/ }).locator('i').click();
  await page.locator('div').filter({ hasText: /^January$/ }).click();
  await page.getByText('May').click();
  await page.getByText('30').click();
  await page.locator('div').filter({ hasText: /^SSN NumberSIN Number$/ }).getByRole('textbox').first().click();
  await page.locator('div').filter({ hasText: /^SSN NumberSIN Number$/ }).getByRole('textbox').first().fill('123');
  await page.locator('div').filter({ hasText: /^SSN NumberSIN Number$/ }).getByRole('textbox').nth(1).click();
  await page.locator('div').filter({ hasText: /^SSN NumberSIN Number$/ }).getByRole('textbox').nth(1).fill('456');
  await page.locator('form').filter({ hasText: 'Employee Full' }).locator('i').nth(1).click();
  await page.getByRole('option', { name: 'Indian' }).click();
  await page.locator('form').filter({ hasText: 'Employee Full' }).locator('i').nth(2).click();
  await page.getByText('Married').click();
  await page.locator('div:nth-child(7) > .oxd-grid-3 > div > .oxd-input-group > div:nth-child(2) > .oxd-input').click();
  await page.locator('form').filter({ hasText: 'Employee Full' }).getByRole('button').click();
});